### ISSUE TITLE
ValueObjectGenerator NullReferenceException on VS 2022 17.6.4

### ISSUE THREAD

**Issue by ebarkalov** [TheArchitectDev/Architect.DomainModeling#18]
Hi @TheArchitectDev 

Thank you so much for such a great library! For some reason, I'm getting NullReferenceException when using ValueObjectGenerator:

```
Warning	CS8785	Generator 'ValueObjectGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'	Domain	D:\Dev\Projects\Solution\Src\Domain\Domain.csproj	1	Active	Generator threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at Architect.DomainModeling.Generator.ValueObjectGenerator.TransformSyntaxNode(GeneratorSyntaxContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass0_0`2.<WrapUserFunction>b__0(TInput input, CancellationToken token)'.
```

Do you have an idea what could be the cause of the problem?

Thank you!

.NET version: 7.0
Visual Studio 2022 version: 17.6.4

**Comment by Timovzl** [comment]
Hi @ebarkalov,

Thanks for your bug report!

If you create a blank solution, add the package, and paste in your ValueObject (working around any compiler errors), do you get the same error from the source generator?

Once we can reproduce it in such a minimal way, could you share the ValueObject so that I can investigate the bug?

**Comment by Timovzl** [comment]
Pity! I was hoping for an easy repro.

In that case, it will probably be quicker if you debug from within your own solution. You can do this as follows:

- Download this package's source.
- In your own project, remove the package reference to DomainModeling.
- Add both the DomainModeling and the DomainModeling.Generator projects to your solution.
- In your own project, add a project reference to DomainModeling.
- In your own project, add an [analyzer project reference](https://github.com/TheArchitectDev/Architect.DomainModeling/blob/2917733fb96ba4b1a797a0185fbd17a3ecda3b94/DomainModeling.Example/DomainModeling.Example.csproj#L16) to DomainModeling.Generator. (You can just modify a regular project reference to match the linked example.)
- Uncomment [this line](https://github.com/TheArchitectDev/Architect.DomainModeling/blob/2917733fb96ba4b1a797a0185fbd17a3ecda3b94/DomainModeling.Generator/SourceGenerator.cs#L28) in your local copy.
- Rebuild.

When you build with the `Debugger.Launch()` line enabled, VS will prompt you for which window to debug in. Hopefully this will reveal the exact line number where the null ref occurs. If not, you can even add a breakpoint to `ValueObjectGenerator.TransformSyntaxNode` to identify the problematic line manually.

Please share any findings, and let's see if we can nip this in the bud.

**Comment by ebarkalov** [comment]
Hi @Timovzl 

I actually found the cause! It seems that ValueObjectGenerator does not like arrays. The following value object makes generator to fail.

```
[SourceGenerated]
public sealed partial class Color : ValueObject
{
  public Color(ushort[] rgb)
  {
    RGB = rgb;
  }

  public ushort[] RGB { get; }
}
```

**Comment by Timovzl** [comment]
There’s an edge case I hadn’t considered. 😄

Great find. I’ll look into this in the next few days. I expect it will be easy to release a new patch version for this.

For now, may I recommend that you take IEnumerable<T> as a parameter and use IReadOnlyList<T> as the property? Assignment can go like this:

`this.Values = values?.ToList() ?? throw new ArgumentNullException(nameof(values));`

As a matter of fact, this will get you a true value object: one that is immutable. The defensive copy also helps ensure that we are not holding a list that the caller could modify after-the-fact.

(For single-valued objects, `WrapperValueObject<T>` can also make life easier.)

**Comment by ebarkalov** [comment]
![image](https://github.com/TheArchitectDev/Architect.DomainModeling/assets/85944367/dc3ea85c-e6c5-416e-ade3-aacb4c752ddd)

tuple.Type.ContainingNamespace is null.

**Comment by ebarkalov** [comment]
> 

Thank you so much! Completely agree. Will do as you suggested!

**Comment by Timovzl** [comment]
@ebarkalov A 2.0.1 prerelease package has been published.

Would you test the fix, please? Perhaps you could confirm that it works well with both your new and your old code - especially the arrays, of course.

**Comment by ebarkalov** [comment]
Hi @Timovzl 

Thank you for the quick fix. I do confirm that arrays are working now in ValueObjects. Had to restart VS after upgrading package to pre-release for error to disappear.

As you mentioned in your comment before, it's better not to use arrays in value objects to support immutability principle. Switched to IReadOnlyList.

Thank you for all the support and such a great library that increases productivity when coding domain objects.
